apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: surveillance

labels:
  - pairs:
      app.kubernetes.io/part-of: disease-surveillance
    includeSelectors: false

resources:
  - namespace.yaml
  - config.yaml
  - postgres.yaml
  - pipeline.yaml
  - api.yaml
  - dashboard.yaml
  - redpanda.yaml
  - flink.yaml
  - producer.yaml
